import './analytics.css';
import Chart from '../../components/charts/Chart';
import { userData, SentenceData } from '../../dummyData';
import CountUp from 'react-countup';

export default function Analytics() {
    return (
        <>
            <div className='Box1'>
                <Chart data={userData} title="User Analytics" grid dataKey="Active User" />
                <Chart data={SentenceData} title="Suggestion Generated/Sentence" grid dataKey="Generated Sentence Ratio" />
                <div className='Box2'>
                    <h3>Most Accepted Suggestion</h3>
                    <h4><CountUp end={125} duration={5} /></h4>

                </div>
                <div className='Box3'>
                    <h3>Most Rejected Suggestion</h3>
                    <h4><CountUp end={93} duration={5} /></h4>

                </div>
                <div className='Box4'>
                    <h3>Suggestions Generated by App</h3>
                    <h4><CountUp end={3000} duration={5} /></h4>

                </div>
                <div className='Box5'>
                    <h3>Total Suggestions Rejected by User</h3>
                    <h4><CountUp end={1200} duration={5} /></h4>

                </div>
            </div>

        </>

    )
}
